insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Striped mullet', 'Aradigm Corporation', 99, true, 'Chinese', 79.07);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Dried milk', 'California Water  Service Group Holding', 77, false, 'Indian', 59.67);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Celeriac', 'Willamette Valley Vineyards, Inc.', 89, true, 'Halal', 52.21);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Cucumber', 'Incyte Corporation', 16, true, 'Western', 46.95);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Skipjack tuna', 'WEC Energy Group, Inc.', 7, false, 'Western', 4.46);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Hummus', 'Laboratory Corporation of America Holdings', 88, true, 'Chinese', 94.92);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Corn grits', 'Preformed Line Products Company', 98, true, 'Vegetarian', 95.65);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pectin', 'Willamette Valley Vineyards, Inc.', 99, true, 'Chinese', 42.59);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Guava', 'Comstock Resources, Inc.', 40, true, 'Indian', 34.56);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Sesbania flower', 'Aradigm Corporation', 51, false, 'Halal', 33.7);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Cauliflower', 'VictoryShares US Small Cap Volatility Wtd ETF', 58, true, 'Western', 36.36);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Green zucchini', 'Commerce Bancshares, Inc.', 25, false, 'Western', 35.32);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Enchilada', 'CGI Group, Inc.', 46, true, 'Indian', 81.21);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Mountain hare', 'Aradigm Corporation', 1, true, 'Malay', 9.18);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Nutritional drink', 'Scudder Strategic Municiple Income Trust', 76, false, 'Japanese', 36.77);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Carrot', 'Scudder Strategic Municiple Income Trust', 58, false, 'Indian', 54.97);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Cottonseed', 'Tuniu Corporation', 90, true, 'Japanese', 17.01);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Custard apple', 'Bed Bath & Beyond Inc.', 12, false, 'Others', 13.52);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Clawed lobster', 'Laboratory Corporation of America Holdings', 10, false, 'Indian', 59.45);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Turnip', 'Tuniu Corporation', 8, true, 'Others', 96.6);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Napa cabbage', 'Tuesday Morning Corp.', 73, true, 'Indian', 94.86);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Common mushroom', 'MBIA, Inc.', 13, false, 'Halal', 61.44);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pikeperch', 'Adient plc', 53, true, 'Japanese', 16.66);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Cardamom', 'Preformed Line Products Company', 52, true, 'Indian', 40.57);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Italian oregano', 'CGI Group, Inc.', 79, true, 'Malay', 28.82);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Beluga whale', 'Callon Petroleum Company', 9, true, 'Western', 15.8);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Conch', 'Willamette Valley Vineyards, Inc.', 32, true, 'Malay', 49.13);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Alfalfa', 'Bed Bath & Beyond Inc.', 17, true, 'Western', 76.31);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Kumquat', 'Willamette Valley Vineyards, Inc.', 64, true, 'Malay', 71.11);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Hot chocolate', 'Bank of America Corporation', 59, true, 'Malay', 21.89);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Jellyfish', 'Willamette Valley Vineyards, Inc.', 4, true, 'Western', 91.14);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Brussel sprouts', 'Willamette Valley Vineyards, Inc.', 97, true, 'Western', 86.56);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pistachio', 'Novan, Inc.', 75, false, 'Chinese', 57.1);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Loganberry', 'Scudder Strategic Municiple Income Trust', 51, false, 'Japanese', 33.41);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Spearmint', 'Willamette Valley Vineyards, Inc.', 24, true, 'Vegetarian', 81.1);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Winged bean', 'Comfort Systems USA, Inc.', 36, false, 'Japanese', 88.77);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Arrowhead', 'Adient plc', 94, true, 'Malay', 23.28);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Rose hip', 'Incyte Corporation', 65, true, 'Malay', 23.59);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Tea leaf willow', 'Novan, Inc.', 66, true, 'Western', 10.24);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Star anise', 'U.S. Global Investors, Inc.', 30, true, 'Japanese', 2.72);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Tapioca pearl', 'Bank of America Corporation', 12, true, 'Halal', 24.03);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Chinese chestnut', 'Aradigm Corporation', 80, true, 'Malay', 51.29);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Morchella (Morel)', 'Aradigm Corporation', 24, true, 'Vegetarian', 22.9);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Garden rhubarb', 'Novan, Inc.', 27, true, 'Malay', 54.44);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Atlantic mackerel', 'Comstock Resources, Inc.', 11, false, 'Japanese', 60.79);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Margarine', 'Adient plc', 12, true, 'Vegetarian', 24.72);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Cichlidae (Tilapia)', 'Aradigm Corporation', 67, true, 'Japanese', 94.64);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Roe', 'Scudder Strategic Municiple Income Trust', 56, true, 'Japanese', 51.04);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Cisco', 'Adient plc', 56, true, 'Japanese', 78.47);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Other candy', 'Burcon NutraScience Corp', 6, true, 'Malay', 66.78);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values (' Whale)', 'Bed Bath & Beyond Inc.', 23, false, 'Japanese', 60.8);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Milk (Human)', 'MBIA, Inc.', 27, false, 'Chinese', 1.13);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Other cereal product', 'U.S. Global Investors, Inc.', 28, false, 'Western', 84.3);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Malabar plum', 'Laboratory Corporation of America Holdings', 27, true, 'Japanese', 4.13);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Barley', 'Lombard Medical, Inc.', 99, false, 'Western', 17.87);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Allspice', 'Bed Bath & Beyond Inc.', 9, true, 'Indian', 27.33);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Spirit', 'NextEra Energy, Inc.', 58, false, 'Others', 34.55);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Japanese pumpkin', 'U.S. Global Investors, Inc.', 73, false, 'Japanese', 95.24);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Wasabi', 'Bank of America Corporation', 17, false, 'Others', 16.39);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Meatloaf', 'PCM, Inc.', 89, true, 'Western', 11.05);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Other bread', 'Regulus Therapeutics Inc.', 29, true, 'Malay', 61.4);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Romaine lettuce', 'Comfort Systems USA, Inc.', 63, false, 'Western', 96.62);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Common buckwheat', 'Adient plc', 2, true, 'Chinese', 48.72);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Bilberry', 'Cumberland Pharmaceuticals Inc.', 95, true, 'Western', 97.54);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Milk (Cow)', 'California Water  Service Group Holding', 52, false, 'Others', 84.33);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Arepa', 'Bank of America Corporation', 83, false, 'Halal', 34.49);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Greater sturgeon', 'Incyte Corporation', 42, false, 'Halal', 81.22);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Atlantic menhaden', 'Royal Caribbean Cruises Ltd.', 62, false, 'Vegetarian', 88.24);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Arrowroot', 'California Water  Service Group Holding', 48, true, 'Japanese', 49.71);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Soursop', 'Aradigm Corporation', 11, false, 'Western', 80.79);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Welsh onion', 'PCM, Inc.', 11, false, 'Western', 4.8);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Ravioli', 'Aradigm Corporation', 17, true, 'Japanese', 46.04);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pear', 'Lombard Medical, Inc.', 20, true, 'Chinese', 29.59);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values (' Pigeon)', 'Incyte Corporation', 42, true, 'Others', 75.65);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Common oregano', 'Burcon NutraScience Corp', 51, false, 'Vegetarian', 38.01);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Sourdock', 'Cumberland Pharmaceuticals Inc.', 64, true, 'Chinese', 90.91);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Wax gourd', 'Aradigm Corporation', 71, false, 'Others', 22.2);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Prickly pear', 'California Water  Service Group Holding', 46, true, 'Halal', 97.06);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Sweet potato', 'Royal Caribbean Cruises Ltd.', 25, true, 'Chinese', 69.98);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Monkfish', 'Callon Petroleum Company', 15, true, 'Western', 31.26);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('True frog', 'Scudder Strategic Municiple Income Trust', 29, true, 'Japanese', 2.39);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pacific oyster', 'California Water  Service Group Holding', 66, false, 'Indian', 46.28);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Garden onion (var.)', 'Tuesday Morning Corp.', 87, true, 'Western', 43.77);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Macadamia nut', 'Burcon NutraScience Corp', 94, false, 'Others', 42.85);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Lasagna', 'Comstock Resources, Inc.', 96, true, 'Vegetarian', 95.43);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Burdock', 'California Water  Service Group Holding', 47, false, 'Japanese', 47.6);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Evergreen huckleberry', 'WEC Energy Group, Inc.', 84, true, 'Western', 22.31);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Tronchuda cabbage', 'California Water  Service Group Holding', 48, true, 'Chinese', 54.87);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Mulberry', 'WEC Energy Group, Inc.', 31, true, 'Halal', 20.59);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Nougat', 'Adient plc', 30, false, 'Malay', 28.11);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Wax gourd', 'Bed Bath & Beyond Inc.', 50, true, 'Chinese', 82.09);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Oriental wheat', 'Scudder Strategic Municiple Income Trust', 7, true, 'Others', 66.3);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Shiitake', 'Aradigm Corporation', 42, true, 'Others', 75.6);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Skipjack tuna', 'NextEra Energy, Inc.', 92, false, 'Indian', 23.79);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Cocoa powder', 'WEC Energy Group, Inc.', 13, false, 'Malay', 93.14);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pulses', 'Comstock Resources, Inc.', 91, false, 'Indian', 34.67);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Icing', 'Comfort Systems USA, Inc.', 95, true, 'Vegetarian', 45.57);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Oxheart cabbage', 'Tuesday Morning Corp.', 69, false, 'Indian', 85.2);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Gadus (Common cod)', 'Tuesday Morning Corp.', 32, false, 'Indian', 77.04);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Peppermint', 'Cumberland Pharmaceuticals Inc.', 33, false, 'Chinese', 88.99);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pili nut', 'Bank of America Corporation', 41, true, 'Western', 63.16);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Tea', 'Comfort Systems USA, Inc.', 34, true, 'Others', 61.45);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Clupeinae (Herring', 'WEC Energy Group, Inc.', 80, true, 'Western', 48.55);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Ascidians', 'U.S. Global Investors, Inc.', 25, true, 'Indian', 90.68);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Snow crab', 'Bank of America Corporation', 33, false, 'Halal', 10.63);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Whisky', 'Bank of America Corporation', 71, true, 'Vegetarian', 59.21);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Sesame', 'Preformed Line Products Company', 99, false, 'Chinese', 18.49);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Vermouth', 'WEC Energy Group, Inc.', 86, false, 'Halal', 3.24);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Syrup', 'MBIA, Inc.', 25, true, 'Vegetarian', 70.0);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values (' Whale)', 'Laboratory Corporation of America Holdings', 13, false, 'Malay', 15.14);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('American shad', 'Incyte Corporation', 77, true, 'Halal', 64.11);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Common carp', 'Preformed Line Products Company', 44, false, 'Western', 11.08);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Raisin bread', 'California Water  Service Group Holding', 40, true, 'Vegetarian', 56.12);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Hibiscus tea', 'WEC Energy Group, Inc.', 27, true, 'Others', 81.22);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Hibiscus tea', 'California Water  Service Group Holding', 16, false, 'Western', 34.25);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Other pasta dish', 'Tuesday Morning Corp.', 32, true, 'Chinese', 38.96);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Multigrain bread', 'Tuniu Corporation', 89, false, 'Japanese', 77.83);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Akutaq', 'Cumberland Pharmaceuticals Inc.', 34, true, 'Halal', 39.73);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('White mustard', 'Burcon NutraScience Corp', 97, false, 'Malay', 97.01);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pepper (C. pubescens)', 'Willamette Valley Vineyards, Inc.', 87, false, 'Malay', 26.68);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Chinese chestnut', 'Preformed Line Products Company', 22, true, 'Indian', 38.45);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Deer', 'Callon Petroleum Company', 83, false, 'Chinese', 12.89);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Green zucchini', 'California Water  Service Group Holding', 28, true, 'Chinese', 64.11);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values (' Rooster)', 'Preformed Line Products Company', 98, true, 'Western', 17.67);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Green zucchini', 'Wells Fargo & Company', 43, false, 'Japanese', 3.59);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Whey', 'U.S. Global Investors, Inc.', 23, false, 'Western', 52.08);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Nuttall cockle', 'Novan, Inc.', 60, false, 'Halal', 88.31);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Bamboo shoots', 'Novan, Inc.', 27, false, 'Malay', 83.07);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Channel catfish', 'Willamette Valley Vineyards, Inc.', 93, true, 'Chinese', 49.26);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Port wine', 'U.S. Global Investors, Inc.', 62, true, 'Indian', 66.53);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Irish moss', 'Scudder Strategic Municiple Income Trust', 18, true, 'Chinese', 7.49);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Polar bear', 'Bank of America Corporation', 9, false, 'Vegetarian', 47.35);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Other cocoa product', 'Laboratory Corporation of America Holdings', 58, true, 'Chinese', 16.74);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Enokitake', 'Preformed Line Products Company', 17, true, 'Chinese', 87.09);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Allium (Onion)', 'Cumberland Pharmaceuticals Inc.', 32, true, 'Others', 5.18);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Watermelon', 'NextEra Energy, Inc.', 32, false, 'Malay', 41.36);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Chinese mustard', 'VictoryShares US Small Cap Volatility Wtd ETF', 21, false, 'Indian', 53.13);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pepper (Capsicum)', 'Wells Fargo & Company', 44, true, 'Indian', 27.84);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Cherry tomato', 'Willamette Valley Vineyards, Inc.', 83, false, 'Others', 40.65);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Black raspberry', 'MBIA, Inc.', 31, true, 'Chinese', 78.02);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Seatrout', 'U.S. Global Investors, Inc.', 45, false, 'Chinese', 61.46);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Grapefruit', 'Bank of America Corporation', 11, true, 'Japanese', 10.52);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Breadnut tree seed', 'Scudder Strategic Municiple Income Trust', 4, false, 'Indian', 49.39);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Sweet potato', 'Royal Caribbean Cruises Ltd.', 39, true, 'Chinese', 58.52);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Thunnus (Common tuna)', 'Commerce Bancshares, Inc.', 82, true, 'Vegetarian', 2.42);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Wax apple', 'U.S. Global Investors, Inc.', 80, true, 'Malay', 34.54);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values (' Tuna)', 'CGI Group, Inc.', 66, true, 'Western', 13.19);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Antelope', 'NextEra Energy, Inc.', 29, false, 'Vegetarian', 2.52);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Haddock', 'U.S. Global Investors, Inc.', 56, false, 'Chinese', 41.12);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Broad bean', 'California Water  Service Group Holding', 80, false, 'Others', 6.16);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Domestic goat', 'Lombard Medical, Inc.', 37, false, 'Halal', 49.51);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Celery leaves', 'Bed Bath & Beyond Inc.', 82, true, 'Malay', 86.78);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Italian oregano', 'Lombard Medical, Inc.', 73, false, 'Japanese', 11.44);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Rocket salad (ssp.)', 'Tuesday Morning Corp.', 11, true, 'Indian', 96.51);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Sesbania flower', 'Bank of America Corporation', 20, true, 'Western', 5.09);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Grapefruit', 'California Water  Service Group Holding', 37, false, 'Halal', 83.04);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Caribou', 'Bed Bath & Beyond Inc.', 85, true, 'Japanese', 24.0);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Carrot', 'Novan, Inc.', 77, true, 'Indian', 60.03);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Baby food', 'Lombard Medical, Inc.', 67, true, 'Indian', 90.63);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Cabbage', 'Willamette Valley Vineyards, Inc.', 68, true, 'Western', 11.47);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Mentha (Mint)', 'Novan, Inc.', 81, false, 'Indian', 38.51);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pomes', 'CGI Group, Inc.', 37, false, 'Japanese', 87.72);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Jerusalem artichoke', 'MBIA, Inc.', 22, false, 'Others', 18.12);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Napa cabbage', 'MBIA, Inc.', 58, true, 'Chinese', 41.71);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Atlantic halibut', 'California Water  Service Group Holding', 78, true, 'Western', 4.04);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Carp bream', 'Tuesday Morning Corp.', 36, false, 'Indian', 20.77);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Icing', 'Adient plc', 90, true, 'Halal', 7.0);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pepper (Capsicum)', 'Regulus Therapeutics Inc.', 89, true, 'Japanese', 75.31);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Blue mussel', 'PCM, Inc.', 68, true, 'Halal', 91.99);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Wax apple', 'Willamette Valley Vineyards, Inc.', 47, true, 'Halal', 52.92);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Red king crab', 'Adient plc', 5, true, 'Halal', 73.19);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Other beverage', 'VictoryShares US Small Cap Volatility Wtd ETF', 18, false, 'Malay', 69.19);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Naranjilla', 'NextEra Energy, Inc.', 25, false, 'Malay', 13.88);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Meatloaf', 'Novan, Inc.', 25, false, 'Halal', 36.83);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Nuts', 'PCM, Inc.', 18, true, 'Indian', 22.28);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Butterfat', 'CGI Group, Inc.', 7, false, 'Western', 35.81);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Leavening agent', 'California Water  Service Group Holding', 64, true, 'Vegetarian', 22.0);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Grapefruit/Pummelo hybrid', 'Royal Caribbean Cruises Ltd.', 95, true, 'Malay', 63.22);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Cake', 'NextEra Energy, Inc.', 36, false, 'Indian', 18.3);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('True frog', 'Tuesday Morning Corp.', 87, false, 'Indian', 18.66);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Agave', 'Comfort Systems USA, Inc.', 29, false, 'Vegetarian', 91.61);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Boysenberry', 'Novan, Inc.', 5, true, 'Others', 66.2);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Roman camomile', 'WEC Energy Group, Inc.', 67, false, 'Chinese', 19.33);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Kefir', 'Callon Petroleum Company', 45, true, 'Others', 55.24);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Dulce de leche', 'U.S. Global Investors, Inc.', 5, true, 'Indian', 64.38);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Potato chip', 'Aradigm Corporation', 94, false, 'Malay', 66.42);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pineapple', 'U.S. Global Investors, Inc.', 12, true, 'Vegetarian', 99.34);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Boysenberry', 'Incyte Corporation', 84, false, 'Vegetarian', 24.11);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Ice cream cone', 'Aradigm Corporation', 94, true, 'Western', 59.46);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Flatfish', 'WEC Energy Group, Inc.', 51, true, 'Vegetarian', 52.79);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Flaxseed', 'California Water  Service Group Holding', 62, true, 'Indian', 87.23);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('European plum', 'NextEra Energy, Inc.', 67, false, 'Others', 91.91);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Roe', 'Incyte Corporation', 82, true, 'Halal', 90.49);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('True sole', 'Commerce Bancshares, Inc.', 27, true, 'Vegetarian', 30.28);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Black huckleberry', 'Comfort Systems USA, Inc.', 17, true, 'Western', 22.97);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Oil-seed Camellia', 'Lombard Medical, Inc.', 86, false, 'Japanese', 10.98);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Small-leaf linden', 'Royal Caribbean Cruises Ltd.', 91, false, 'Others', 73.95);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Other cocoa product', 'VictoryShares US Small Cap Volatility Wtd ETF', 66, false, 'Malay', 43.84);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Sesbania flower', 'Incyte Corporation', 18, false, 'Halal', 28.1);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Monkfish', 'U.S. Global Investors, Inc.', 27, true, 'Halal', 78.44);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Other cocoa product', 'Adient plc', 88, true, 'Chinese', 2.19);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Nutmeg', 'Royal Caribbean Cruises Ltd.', 21, true, 'Japanese', 50.26);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Salt', 'California Water  Service Group Holding', 34, false, 'Others', 42.16);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pacific salmon', 'Tuniu Corporation', 19, false, 'Malay', 16.42);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Squab', 'Aradigm Corporation', 21, false, 'Others', 52.07);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Freshwater eel', 'Lombard Medical, Inc.', 86, false, 'Malay', 94.11);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Buffalo', 'VictoryShares US Small Cap Volatility Wtd ETF', 51, true, 'Japanese', 51.34);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('American pokeweed', 'Bed Bath & Beyond Inc.', 19, false, 'Halal', 26.59);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Potato bread', 'VictoryShares US Small Cap Volatility Wtd ETF', 91, true, 'Western', 45.24);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Squashberry', 'California Water  Service Group Holding', 29, true, 'Malay', 55.69);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Roe', 'Callon Petroleum Company', 64, false, 'Malay', 59.08);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Tostada', 'Tuniu Corporation', 79, false, 'Japanese', 49.9);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pitanga', 'Incyte Corporation', 93, true, 'Halal', 16.87);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Ucuhuba', 'Lombard Medical, Inc.', 20, false, 'Indian', 14.63);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Meringue', 'Burcon NutraScience Corp', 46, true, 'Malay', 8.66);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Bitter gourd', 'CGI Group, Inc.', 27, false, 'Japanese', 7.86);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Natal plum', 'Wells Fargo & Company', 68, false, 'Japanese', 76.84);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Canola', 'Lombard Medical, Inc.', 90, false, 'Halal', 44.97);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Elderberry', 'Cumberland Pharmaceuticals Inc.', 14, false, 'Western', 54.27);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Boysenberry', 'Adient plc', 28, true, 'Others', 68.36);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Succotash', 'Comstock Resources, Inc.', 56, false, 'Western', 53.34);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Lentils', 'Wells Fargo & Company', 83, true, 'Chinese', 83.51);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Remoulade', 'Royal Caribbean Cruises Ltd.', 90, true, 'Western', 10.03);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Fats and oils', 'MBIA, Inc.', 96, true, 'Western', 63.33);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Whelk', 'NextEra Energy, Inc.', 42, true, 'Western', 3.76);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Atlantic pollock', 'Comfort Systems USA, Inc.', 55, false, 'Indian', 91.02);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Cisco', 'Tuniu Corporation', 18, false, 'Others', 23.97);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Horseradish', 'Laboratory Corporation of America Holdings', 17, true, 'Halal', 22.99);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Freshwater eel', 'Adient plc', 80, true, 'Western', 62.03);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Parsnip', 'CGI Group, Inc.', 90, true, 'Halal', 38.79);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Chinese mustard', 'U.S. Global Investors, Inc.', 87, false, 'Western', 18.58);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Mule deer', 'Lombard Medical, Inc.', 34, true, 'Halal', 40.94);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Lard', 'Novan, Inc.', 71, false, 'Malay', 36.65);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Whey', 'Bank of America Corporation', 95, true, 'Chinese', 54.82);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Couscous', 'Burcon NutraScience Corp', 40, true, 'Malay', 63.08);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Lemon grass', 'Novan, Inc.', 82, true, 'Western', 95.05);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values (' Trout)', 'Laboratory Corporation of America Holdings', 21, true, 'Vegetarian', 89.34);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pistachio', 'Comfort Systems USA, Inc.', 86, true, 'Japanese', 11.6);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pudding', 'Royal Caribbean Cruises Ltd.', 59, false, 'Halal', 49.24);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Other fruit product', 'Royal Caribbean Cruises Ltd.', 51, true, 'Others', 3.66);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Crisp bread', 'Preformed Line Products Company', 5, true, 'Chinese', 52.92);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Grass pea', 'CGI Group, Inc.', 38, true, 'Halal', 43.3);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Spearmint', 'Scudder Strategic Municiple Income Trust', 59, true, 'Indian', 35.58);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Sheepshead', 'Incyte Corporation', 56, false, 'Vegetarian', 74.58);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Watercress', 'Incyte Corporation', 14, true, 'Western', 36.18);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Celeriac', 'Wells Fargo & Company', 45, false, 'Others', 67.28);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Mule deer', 'Laboratory Corporation of America Holdings', 15, true, 'Others', 54.19);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Orange roughy', 'WEC Energy Group, Inc.', 36, true, 'Halal', 67.49);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Green bean', 'Tuesday Morning Corp.', 12, true, 'Chinese', 64.74);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values (' Halibut', 'Regulus Therapeutics Inc.', 58, false, 'Malay', 7.15);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Other cereal product', 'Callon Petroleum Company', 62, false, 'Vegetarian', 44.98);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Ginseng', 'Aradigm Corporation', 22, false, 'Halal', 77.73);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Turkey', 'Comfort Systems USA, Inc.', 29, false, 'Indian', 5.64);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Lemon verbena', 'CGI Group, Inc.', 95, true, 'Halal', 47.17);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values (' Swan)', 'Bed Bath & Beyond Inc.', 59, false, 'Vegetarian', 90.88);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values (' Sprat)', 'Bank of America Corporation', 95, true, 'Japanese', 9.25);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Molasses', 'Tuniu Corporation', 58, true, 'Malay', 52.53);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Herbs and Spices', 'Regulus Therapeutics Inc.', 66, true, 'Malay', 52.27);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Beefalo', 'California Water  Service Group Holding', 4, false, 'Halal', 22.1);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Morchella (Morel)', 'MBIA, Inc.', 42, true, 'Western', 79.7);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Feijoa', 'Lombard Medical, Inc.', 99, true, 'Malay', 16.23);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values (' Goose', 'Callon Petroleum Company', 88, false, 'Halal', 48.13);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Freshwater eel', 'Novan, Inc.', 3, false, 'Japanese', 31.48);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Common octopus', 'VictoryShares US Small Cap Volatility Wtd ETF', 11, true, 'Vegetarian', 42.35);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Mexican oregano', 'Comstock Resources, Inc.', 60, true, 'Vegetarian', 80.48);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Sweet orange', 'WEC Energy Group, Inc.', 97, false, 'Western', 72.67);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Yellow pond-lily', 'VictoryShares US Small Cap Volatility Wtd ETF', 15, true, 'Chinese', 65.55);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Chewing gum', 'Bank of America Corporation', 7, false, 'Malay', 16.16);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Biscuit', 'Comfort Systems USA, Inc.', 41, false, 'Indian', 43.49);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Jute', 'California Water  Service Group Holding', 99, true, 'Halal', 85.05);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Kelp', 'VictoryShares US Small Cap Volatility Wtd ETF', 66, false, 'Others', 58.07);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Butter substitute', 'CGI Group, Inc.', 84, true, 'Halal', 54.64);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Enokitake', 'Lombard Medical, Inc.', 85, true, 'Halal', 47.12);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Milk substitute', 'Bed Bath & Beyond Inc.', 45, true, 'Malay', 90.67);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Eggs', 'Royal Caribbean Cruises Ltd.', 66, false, 'Western', 38.17);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Sweet cherry', 'U.S. Global Investors, Inc.', 4, false, 'Others', 14.26);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Channel catfish', 'Aradigm Corporation', 43, true, 'Chinese', 39.08);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Acorn', 'Scudder Strategic Municiple Income Trust', 37, false, 'Malay', 86.99);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Japanese chestnut', 'NextEra Energy, Inc.', 9, true, 'Western', 16.06);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Winged bean', 'Aradigm Corporation', 65, true, 'Japanese', 17.13);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Jostaberry', 'Novan, Inc.', 43, true, 'Western', 83.64);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Black bear', 'VictoryShares US Small Cap Volatility Wtd ETF', 24, false, 'Indian', 25.12);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Welsh onion', 'WEC Energy Group, Inc.', 96, false, 'Halal', 91.51);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Other soy product', 'Bed Bath & Beyond Inc.', 27, true, 'Malay', 56.7);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Almond', 'Comfort Systems USA, Inc.', 51, false, 'Vegetarian', 17.51);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Spearmint', 'Incyte Corporation', 50, false, 'Japanese', 11.04);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Blackcurrant', 'Tuesday Morning Corp.', 7, false, 'Indian', 73.48);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Catfish', 'Callon Petroleum Company', 76, true, 'Chinese', 13.28);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Kombu', 'Preformed Line Products Company', 90, true, 'Western', 27.08);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Sugar substitute', 'Callon Petroleum Company', 31, true, 'Western', 45.73);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Common beet', 'U.S. Global Investors, Inc.', 35, false, 'Malay', 27.74);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pili nut', 'Comstock Resources, Inc.', 52, true, 'Chinese', 96.06);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Other wine', 'Callon Petroleum Company', 37, false, 'Others', 41.85);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Chicory roots', 'Cumberland Pharmaceuticals Inc.', 95, true, 'Malay', 48.93);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Carp bream', 'Lombard Medical, Inc.', 75, false, 'Halal', 86.27);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Dulce de leche', 'Tuniu Corporation', 48, false, 'Japanese', 63.69);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Root vegetables', 'CGI Group, Inc.', 3, true, 'Western', 32.11);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pulses', 'Tuesday Morning Corp.', 2, false, 'Chinese', 52.97);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Sweet basil', 'Comstock Resources, Inc.', 25, false, 'Japanese', 53.43);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values (' Pork)', 'Comfort Systems USA, Inc.', 98, true, 'Western', 49.71);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Chocolate mousse', 'PCM, Inc.', 14, false, 'Others', 32.53);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Yellowfin tuna', 'Preformed Line Products Company', 88, true, 'Halal', 39.65);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Turmeric', 'Cumberland Pharmaceuticals Inc.', 84, false, 'Indian', 78.85);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Silver linden', 'Comfort Systems USA, Inc.', 19, false, 'Others', 77.84);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Nuttall cockle', 'Tuesday Morning Corp.', 88, false, 'Indian', 90.89);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Swede', 'Aradigm Corporation', 62, true, 'Halal', 11.02);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Black mulberry', 'Adient plc', 53, false, 'Halal', 30.98);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Millet', 'Burcon NutraScience Corp', 7, true, 'Japanese', 62.48);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Herbs and Spices', 'CGI Group, Inc.', 61, false, 'Chinese', 90.25);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Poppy', 'CGI Group, Inc.', 9, false, 'Malay', 95.4);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Heart of palm', 'U.S. Global Investors, Inc.', 63, true, 'Western', 62.04);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Blue crab', 'Comfort Systems USA, Inc.', 55, false, 'Indian', 61.63);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Mulberry', 'U.S. Global Investors, Inc.', 41, true, 'Indian', 41.73);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Percoidei (Bass and others)', 'Aradigm Corporation', 90, true, 'Japanese', 25.27);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pacific rockfish', 'Comfort Systems USA, Inc.', 95, true, 'Others', 61.74);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Casein', 'WEC Energy Group, Inc.', 63, true, 'Vegetarian', 62.04);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Ginseng', 'CGI Group, Inc.', 87, true, 'Japanese', 35.84);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Black crowberry', 'Aradigm Corporation', 94, true, 'Indian', 46.06);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pita bread', 'Scudder Strategic Municiple Income Trust', 65, true, 'Japanese', 68.86);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Mammee apple', 'PCM, Inc.', 55, true, 'Halal', 99.11);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Sockeye salmon', 'U.S. Global Investors, Inc.', 44, false, 'Others', 30.5);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Japanese persimmon', 'Bed Bath & Beyond Inc.', 30, true, 'Western', 14.59);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Atlantic herring', 'Tuesday Morning Corp.', 64, true, 'Malay', 21.6);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Cornbread', 'Commerce Bancshares, Inc.', 48, false, 'Chinese', 14.84);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pulses', 'CGI Group, Inc.', 71, true, 'Others', 98.33);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Parsley', 'CGI Group, Inc.', 47, false, 'Indian', 20.53);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Buttermilk', 'Callon Petroleum Company', 74, false, 'Others', 91.99);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Chinese bayberry', 'Tuesday Morning Corp.', 23, false, 'Others', 90.37);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Wild rice', 'Comfort Systems USA, Inc.', 83, false, 'Malay', 34.28);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Prunus (Cherry', 'Preformed Line Products Company', 98, false, 'Japanese', 47.01);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Ravioli', 'Scudder Strategic Municiple Income Trust', 49, true, 'Western', 30.26);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Domestic pig (Piglet', 'Preformed Line Products Company', 46, true, 'Indian', 61.21);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Egg substitute', 'Tuniu Corporation', 3, false, 'Malay', 26.32);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Japanese persimmon', 'CGI Group, Inc.', 66, true, 'Chinese', 99.43);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Tortilla chip', 'Scudder Strategic Municiple Income Trust', 93, false, 'Others', 5.51);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Cassava', 'Lombard Medical, Inc.', 28, false, 'Japanese', 52.45);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Tamale', 'CGI Group, Inc.', 98, true, 'Japanese', 14.91);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Parsley', 'Adient plc', 95, true, 'Japanese', 12.46);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pie', 'Royal Caribbean Cruises Ltd.', 84, true, 'Others', 87.25);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Chili', 'MBIA, Inc.', 40, false, 'Western', 15.84);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('French plantain', 'Tuniu Corporation', 69, true, 'Japanese', 9.12);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Peach (var.)', 'NextEra Energy, Inc.', 39, true, 'Indian', 11.07);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Durian', 'Commerce Bancshares, Inc.', 88, false, 'Indian', 8.3);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Wild rice', 'Adient plc', 14, true, 'Japanese', 24.7);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Horned melon', 'Bed Bath & Beyond Inc.', 66, true, 'Vegetarian', 67.64);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Red bell pepper', 'WEC Energy Group, Inc.', 21, true, 'Malay', 17.42);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Rice bread', 'Royal Caribbean Cruises Ltd.', 75, true, 'Japanese', 48.71);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Cream substitute', 'Willamette Valley Vineyards, Inc.', 26, false, 'Others', 73.75);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pheasant', 'Tuesday Morning Corp.', 27, false, 'Japanese', 34.67);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Oat', 'Laboratory Corporation of America Holdings', 95, false, 'Halal', 11.99);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Clupeinae (Herring', 'CGI Group, Inc.', 20, false, 'Western', 45.05);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Acerola', 'California Water  Service Group Holding', 20, false, 'Halal', 23.33);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Hamburger', 'Royal Caribbean Cruises Ltd.', 13, false, 'Others', 64.25);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Sesbania flower', 'WEC Energy Group, Inc.', 29, true, 'Chinese', 14.59);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Lemon grass', 'PCM, Inc.', 33, true, 'Chinese', 4.62);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Mexican groundcherry', 'Commerce Bancshares, Inc.', 12, true, 'Halal', 71.04);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Cheese', 'Adient plc', 40, false, 'Others', 22.67);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Eastern oyster', 'Wells Fargo & Company', 79, false, 'Malay', 12.58);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Common wheat', 'U.S. Global Investors, Inc.', 5, false, 'Chinese', 45.26);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Percoidei (Bass and others)', 'Incyte Corporation', 74, false, 'Malay', 48.28);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Wheat bread', 'California Water  Service Group Holding', 19, false, 'Western', 93.49);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Hyacinth bean', 'Wells Fargo & Company', 88, true, 'Western', 82.11);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Rainbow smelt', 'VictoryShares US Small Cap Volatility Wtd ETF', 24, false, 'Vegetarian', 75.28);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Deer', 'VictoryShares US Small Cap Volatility Wtd ETF', 41, false, 'Halal', 77.36);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Kumquat', 'Regulus Therapeutics Inc.', 38, true, 'Malay', 50.03);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Sausage', 'Commerce Bancshares, Inc.', 2, true, 'Others', 85.11);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Skunk currant', 'Adient plc', 51, false, 'Vegetarian', 44.36);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Liquor', 'Commerce Bancshares, Inc.', 58, true, 'Western', 17.7);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Watercress', 'Royal Caribbean Cruises Ltd.', 59, false, 'Chinese', 90.19);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Irish moss', 'Willamette Valley Vineyards, Inc.', 37, false, 'Indian', 25.91);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('European plum', 'CGI Group, Inc.', 35, false, 'Vegetarian', 19.31);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Irish moss', 'Bank of America Corporation', 98, true, 'Others', 48.87);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Madeira wine', 'Royal Caribbean Cruises Ltd.', 98, true, 'Halal', 95.46);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Crayfish', 'California Water  Service Group Holding', 36, false, 'Halal', 53.37);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Rye', 'Incyte Corporation', 25, true, 'Chinese', 57.98);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Jostaberry', 'Scudder Strategic Municiple Income Trust', 61, true, 'Others', 55.59);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Persimmon', 'Aradigm Corporation', 31, true, 'Malay', 59.58);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Cocktail', 'NextEra Energy, Inc.', 92, true, 'Vegetarian', 10.21);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Nutmeg', 'Royal Caribbean Cruises Ltd.', 16, true, 'Japanese', 42.18);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Herbs and Spices', 'U.S. Global Investors, Inc.', 21, false, 'Western', 60.24);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Horseradish tree', 'WEC Energy Group, Inc.', 35, true, 'Malay', 74.26);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Other sandwich', 'Wells Fargo & Company', 2, true, 'Western', 12.94);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('European anchovy', 'Comstock Resources, Inc.', 48, true, 'Halal', 35.49);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Lettuce', 'Callon Petroleum Company', 59, true, 'Others', 19.51);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Arctic blackberry', 'Commerce Bancshares, Inc.', 6, false, 'Vegetarian', 41.58);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Cowpea', 'Tuesday Morning Corp.', 73, false, 'Indian', 28.23);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Frybread', 'Aradigm Corporation', 58, false, 'Malay', 19.91);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Cloudberry', 'CGI Group, Inc.', 78, false, 'Malay', 89.92);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Fudge', 'Tuesday Morning Corp.', 82, true, 'Vegetarian', 81.52);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Meringue', 'Scudder Strategic Municiple Income Trust', 14, false, 'Vegetarian', 56.54);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Soy milk', 'NextEra Energy, Inc.', 52, false, 'Vegetarian', 16.82);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values (' Hen', 'Laboratory Corporation of America Holdings', 21, true, 'Others', 3.52);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Dripping', 'CGI Group, Inc.', 33, false, 'Western', 62.69);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Robusta coffee', 'Bank of America Corporation', 62, false, 'Indian', 66.91);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Pigeon pea', 'Burcon NutraScience Corp', 35, false, 'Western', 80.46);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Other wine', 'Comfort Systems USA, Inc.', 58, false, 'Vegetarian', 82.15);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Passion fruit', 'Scudder Strategic Municiple Income Trust', 51, false, 'Japanese', 15.73);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Soy cream', 'MBIA, Inc.', 65, true, 'Western', 24.56);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values ('Herbs and Spices', 'WEC Energy Group, Inc.', 66, true, 'Indian', 89.45);
insert into Foods (fname, rname, dailylimit, isavailable, category, price) values (' Goose', 'MBIA, Inc.', 82, true, 'Halal', 67.99);
